
allow_anonymous true



persistence true
persistence_location /mosquitto/data/
autosave_interval 30
autosave_on_changes false


log_dest stdout
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S


listener 1883 0.0.0.0
protocol mqtt


listener 9001 0.0.0.0
protocol websockets


max_connections -1
message_size_limit 10485760
max_inflight_messages 100
max_queued_messages 10000